import os

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
LIQPAY_PUBLIC_KEY = os.getenv("LIQPAY_PUBLIC_KEY")
LIQPAY_PRIVATE_KEY = os.getenv("LIQPAY_PRIVATE_KEY")
NAKRUTKA_API_KEY = os.getenv("NAKRUTKA_API_KEY")
