services:
  - type: worker
    name: telegram-nakrutka-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python nakrutka_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
